### ISSUE TITLE
BGP on a separate Ryu-app

### ISSUE THREAD

**Issue by trungdtbk** [REANNZ/faucet#130] opened 2016-07-27 08:36 UTC
I think bgp should be on a separate ryu app. It will be a central point to peer with all neighbors and handle bgp logic. Faucet will be responsible for converting and install fib entries.
If bgp is not needed, we just need not to run bgp app.
I'm now working on it.

**Comment by anarkiwi** [comment] 2016-07-27 08:45
I'm confused. If you don't configure BGP, it does not even start BGP. There
is no need to remove it. As I explained in the change you can run Quagga to
do more advanced processing.

**Comment by anarkiwi** [comment] 2016-07-27 08:53
Also. BGP is intend solely as a FIB programming interface. It is not
intended as a general purpose solution. It needs to be inside FAUCET so
that an external system like Quagga can interface with it. Happy to explain
further.

**Comment by trungdtbk** [comment] 2016-07-27 18:06
I understand. But I mean having an implementation of BGP we can take more control over it. For example, the app can take traffic load as input to the route selection algorithm.

**Comment by anarkiwi** [comment] 2016-07-27 18:53
Exactly why I intend an external processor to do that. There is no need to
build that into FAUCET. Again, the BGP that is there is just to program the
FIB. There is no reason why you couldn't build a complex policy router with
exabgp (say). It then outputs the final FIB to FAUCET.

**Comment by anarkiwi** [comment] 2016-07-31 02:39
Closed as working as intended and external processing is already supported.

**Closed by anarkiwi** 2016-07-31 02:39 UTC
