### ISSUE TITLE
FAUCET pypi package doesn't install PBR

### ISSUE THREAD

**Issue by gizmoguy** [REANNZ/faucet#724] opened 2017-06-18 05:36 UTC
We have PBR set as in setup_requires however when we "pip install faucet" on a fresh machine we get something like this:

`pkg_resources.DistributionNotFound: The 'pbr>=1.9' distribution was not found and is required by the application`

Work around for now is to "pip install --upgrade pbr" before installing faucet.

Workout how to properly add PBR as a dependency so pip installs it.

**Comment by reidrac** [comment] 2017-07-25 08:31
If I remove the version requirement in "setup_requires" in setup.py, it works as expected.

According to pbr docs, they don't include a minimal pbr version: https://docs.openstack.org/pbr/latest/user/using.html

I upgraded setuptools and pip to the latest available version, so this could be a bug in one of them.

Why is is a minimal pbr version required?

**Comment by reidrac** [comment] 2017-07-25 08:50
OK, I got what is going on!
```
$ pip install .
Processing .../faucet
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-LRUpVz-build/.eggs/pbr-1.5.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-LRUpVz-build/setup.py", line 63, in <module>
        pbr=True
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File ".../faucet/ENV/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File ".../faucet/ENV/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File ".../faucet/ENV/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pbr>=1.9' distribution was not found and is required by the application
```
So pbr is not installed, setuptools runs easy_install to get it to a tmp .egg directory, but the version it gets is 1.5.4 and that conflicts with the >= 1.9 requirement.

**Comment by reidrac** [comment] 2017-07-25 09:03
Well, easy_install seems to do the right thing:

```
$ easy_install -n "pbr>=1.9"
Searching for pbr>=1.9
Reading https://pypi.python.org/simple/pbr/
Best match: pbr 3.1.1
Downloading https://pypi.python.org/packages/d5/d6/f2bf137d71e4f213b575faa9eb426a8775732432edb67588a8ee836ecb80/pbr-3.1.1.tar.gz#md5=4e82c2e07af544c56a5b71c801525b00
Processing pbr-3.1.1.tar.gz
Writing /tmp/easy_install-zNEBtv/pbr-3.1.1/setup.cfg
Running pbr-3.1.1/setup.py -n -q bdist_egg --dist-dir /tmp/easy_install-zNEBtv/pbr-3.1.1/egg-dist-tmp-RbEVMo
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
```

But when pip tries to solve the dependency of setup_requires, it gets an old version of pbr.

**Comment by reidrac** [comment] 2017-07-25 09:09
... and the pbr version we get happens to be the version of faucet; the problem is line 50 of setup.py that is setting the PBR_VERSION env variable and is confusing pip.

**Comment by reidrac** [comment] 2017-07-25 09:22
This is the issue: https://bugs.launchpad.net/pbr/+bug/1256138

**Comment by reidrac** [comment] 2017-07-25 09:53
I opened a PR but I don't like the solution specially. This needs to be fixed in pbr by providing a more sensible way of forcing the package version without using environment variables perhaps.

So what I'm offering is a temp workaround. Sorry :(

**Closed** 2017-07-26 01:25 UTC

**Comment by gizmoguy** [comment] 2017-07-26 01:35
Ah yes, that looks to be quite the annoying bug! PBR is great at simplifying packaging but isn't without its issues.

I think your fix is fine for now and seems to be passing tests so I've merged it in.

Thanks again for looking at this bug for us!

**Comment by reidrac** [comment] 2017-07-26 06:09
Thank your for Faucet!

**Comment by anarkiwi** [comment] 2017-07-26 06:29
Thank you sir - if you have time to let us know what you find it useful
for, and if there's anything you would especially like, please do let us
know.
